[package]
name = "yosoi-document-locator-benchmarks"
version = "0.1.0-rc.3"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
autobenches = false

[dev-dependencies]
criterion = { workspace = true, features = ["cargo_bench_support", "plotters"] }
divan.workspace = true
serde_json.workspace = true
yosoi-documents.workspace = true

[[bench]]
name = "criterion_documents"
harness = false

[[bench]]
name = "criterion_json"
harness = false

[[bench]]
name = "criterion_document_locators"
harness = false

[[bench]]
name = "document_locators"
harness = false

[[bench]]
name = "allocation_document_locators"
harness = false

[lints]
workspace = true
