"""Type stubs for the yosoi_driver native extension module."""

from __future__ import annotations

class Page:
    """A browser page / tab. All methods are async."""

    async def navigate(self, url: str) -> None: ...
    async def wait_for_navigation(self) -> None: ...
    async def content(self) -> str: ...
    async def title(self) -> str | None: ...
    async def url(self) -> str | None: ...
    async def evaluate_js(self, expression: str) -> str:
        """Evaluate JS and return result as JSON string."""
        ...
    async def screenshot_png(self) -> bytes: ...
    async def pdf_bytes(self) -> bytes: ...
    async def query_selector(self, selector: str) -> str | None: ...
    async def query_selector_all(self, selector: str) -> list[str]: ...
    async def click_element(self, selector: str) -> None: ...
    async def type_into(self, selector: str, text: str) -> None: ...
    async def set_headers(self, headers: dict[str, str]) -> None: ...
    async def close(self) -> None: ...

class BrowserSession:
    """Browser session wrapping a Chromium instance via CDP.

    Supports ``async with`` context manager protocol.

    Example::

        async with BrowserSession() as browser:
            page = await browser.new_page("https://example.com")
            html = await page.content()
    """

    def __init__(
        self,
        *,
        headless: bool = True,
        ws_url: str | None = None,
        stealth: bool = True,
        no_sandbox: bool = False,
        proxy: str | None = None,
        chrome_executable: str | None = None,
        extra_args: list[str] | None = None,
    ) -> None: ...
    async def launch(self) -> None: ...
    async def new_page(self, url: str) -> Page: ...
    async def version(self) -> str: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> BrowserSession: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_val: BaseException | None = None,
        exc_tb: object = None,
    ) -> bool: ...
