[package]
name = "xtask"
version = "0.1.2"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
semver = "1"
toml_edit = "0.22"

[lints]
workspace = true
