//! Immutable, cross-field-validated Web Capture aggregate.

use chrono::TimeDelta;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use yosoi_types::{ActivityOutcome, ArtifactAvailability, CaptureId};

use crate::{
    AcquisitionCapabilityProfile, ArtifactCapability, ArtifactFamilyResult, ArtifactMultiplicity,
    BrowserArtifactContext, BrowserChallengeFact, BrowserExecutionReceipt,
    BrowserVisualLayoutCorrelation, CaptureEnvironment, CaptureTermination, WebAcquisitionRecord,
    WebArtifact, WebArtifactFamily, WebArtifactManifest, WebArtifactRelationship,
    WebArtifactResults, WebProviderCapabilityProfile,
};

mod browser;
mod serialization;

use browser::{validate_browser_challenge, validate_browser_execution};

/// Whether every requested part of a finalized capture completed.
///
/// Incompleteness is valid; terminal facts retain its detailed reasons.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CaptureCompleteness {
    /// The activity succeeded, observation ended normally, and every requested
    /// artifact family was captured completely.
    Complete,
    /// Useful final evidence exists, but at least one requested part did not
    /// complete or observation ended at a bound or interruption.
    Incomplete,
}

/// Error returned when individually valid capture facts contradict each other.
#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
pub enum WebCaptureError {
    /// The capability profile describes a different acquisition mechanism.
    #[error("capability acquisition profile must match the capture strategy")]
    AcquisitionCapabilityMismatch,
    /// The environment kind cannot describe the acquisition mechanism.
    #[error("capture environment must match the acquisition strategy")]
    EnvironmentMismatch,
    /// A known browser mode disagrees with the capability profile.
    #[error("known browser mode must match the browser capability profile")]
    BrowserModeMismatch,
    /// The declared capability producer is not the environment's executor.
    #[error("capability producer must match the environment executor")]
    CapabilityProducerMismatch,
    /// A family result contradicts declared provider support.
    #[error("{family:?} result contradicts its declared capability")]
    CapabilityResultMismatch { family: WebArtifactFamily },
    /// A produced family exceeds its declared logical multiplicity.
    #[error("{family:?} artifacts exceed the declared multiplicity")]
    ArtifactMultiplicityExceeded { family: WebArtifactFamily },
    /// An artifact was generated by another activity.
    #[error("every web artifact must be generated by the containing capture")]
    ForeignArtifact,
    /// An artifact generation timestamp is outside the observation window.
    #[error("artifact generation time must fall within the capture observation window")]
    ArtifactTimeOutsideWindow,
    /// Two manifest entries use the same capture-local artifact identity.
    #[error("web artifact identities must be unique within a capture")]
    DuplicateArtifact,
    /// Receipt outputs and typed manifest artifacts do not describe the same set.
    #[error("capture receipt outputs must exactly match typed manifest artifacts")]
    ReceiptOutputMismatch,
    /// A browser execution receipt was produced for another capture activity.
    #[error("browser execution receipt must be bound to the containing capture")]
    ForeignBrowserExecution,
    /// A managed browser receipt requires a browser acquisition strategy.
    #[error("browser execution receipt requires a browser acquisition strategy")]
    BrowserExecutionStrategyMismatch,
    /// A managed browser receipt requires a browser capture environment.
    #[error("browser execution receipt requires a browser capture environment")]
    BrowserExecutionEnvironmentMismatch,
    /// A challenge fact requires a browser acquisition strategy.
    #[error("browser challenge fact requires a browser acquisition strategy")]
    BrowserChallengeStrategyMismatch,
    /// A challenge fact requires a browser capture environment.
    #[error("browser challenge fact requires a browser capture environment")]
    BrowserChallengeEnvironmentMismatch,
    /// A serialized challenge fact contains contradictory states or evidence.
    #[error("browser challenge fact is internally inconsistent")]
    InvalidBrowserChallenge,
    /// A semantic relationship points outside the manifest.
    #[error("artifact relationships must reference artifacts in the containing capture")]
    ForeignRelationship,
    /// Browser-only payload context is absent, misplaced, or inconsistent with provenance.
    #[error("artifact browser context must match its family, environment, and generation time")]
    BrowserArtifactContextMismatch,
    /// Serialized completeness did not match the facts from which it is derived.
    #[error("capture completeness must match its receipt, termination, and artifact results")]
    CompletenessMismatch,
}

/// One immutable finalized web capture.
///
/// Fields are private and there are no mutating accessors. Construction and
/// deserialization both run the same cross-field validation. `PartialEq`
/// compares every represented fact, including occurrence identities and wall
/// clock timestamps; [`crate::WebCaptureWire::identity_digest`] provides the
/// separate, volatility-excluding semantic identity defined by the v1 wire
/// contract.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct WebCapture {
    acquisition: WebAcquisitionRecord,
    environment: CaptureEnvironment,
    observation: crate::CaptureObservation,
    capabilities: WebProviderCapabilityProfile,
    artifacts: WebArtifactManifest,
    relationships: Vec<WebArtifactRelationship>,
    completeness: CaptureCompleteness,
    #[serde(skip_serializing_if = "Option::is_none")]
    browser_execution: Option<BrowserExecutionReceipt>,
    #[serde(skip_serializing_if = "Option::is_none")]
    browser_challenge: Option<BrowserChallengeFact>,
}

impl WebCapture {
    /// Finalizes validated component values into one immutable capture.
    pub fn finalize(
        acquisition: WebAcquisitionRecord,
        environment: CaptureEnvironment,
        observation: crate::CaptureObservation,
        capabilities: WebProviderCapabilityProfile,
        artifacts: WebArtifactManifest,
        relationships: Vec<WebArtifactRelationship>,
    ) -> Result<Self, WebCaptureError> {
        validate_execution(&acquisition, &environment, &capabilities)?;
        validate_capabilities(capabilities.artifacts(), artifacts.results())?;
        validate_artifacts(
            &acquisition,
            &environment,
            &observation,
            &artifacts,
            &relationships,
        )?;
        let completeness = derive_completeness(&acquisition, &observation, artifacts.results());
        Ok(Self {
            acquisition,
            environment,
            observation,
            capabilities,
            artifacts,
            relationships,
            completeness,
            browser_execution: None,
            browser_challenge: None,
        })
    }

    /// Returns the occurrence identity of this capture attempt.
    pub const fn id(&self) -> CaptureId {
        self.acquisition.receipt().id()
    }

    /// Returns target, resolution, and terminal acquisition receipt.
    pub const fn acquisition(&self) -> &WebAcquisitionRecord {
        &self.acquisition
    }

    /// Returns the effective, secret-safe execution environment.
    pub const fn environment(&self) -> &CaptureEnvironment {
        &self.environment
    }

    /// Returns the bounded observation record.
    pub const fn observation(&self) -> &crate::CaptureObservation {
        &self.observation
    }

    /// Returns the provider capabilities used to interpret results.
    pub const fn capabilities(&self) -> &WebProviderCapabilityProfile {
        &self.capabilities
    }

    /// Returns requested artifact families and their final outcomes.
    pub const fn artifacts(&self) -> &WebArtifactManifest {
        &self.artifacts
    }

    /// Returns capture-local semantic artifact relationships.
    pub fn relationships(&self) -> &[WebArtifactRelationship] {
        &self.relationships
    }

    /// Returns the durable execution receipt when this capture used a managed browser lease.
    pub const fn browser_execution(&self) -> Option<&BrowserExecutionReceipt> {
        self.browser_execution.as_ref()
    }

    /// Returns the neutral anti-bot presence and active-challenge observation.
    pub const fn browser_challenge(&self) -> Option<&BrowserChallengeFact> {
        self.browser_challenge.as_ref()
    }

    /// Attaches the complete execution receipt to the exact browser capture that owned it.
    pub fn with_browser_execution(
        mut self,
        receipt: BrowserExecutionReceipt,
    ) -> Result<Self, WebCaptureError> {
        validate_browser_execution(&self.acquisition, &self.environment, &receipt)?;
        self.browser_execution = Some(receipt);
        Ok(self)
    }

    /// Attaches a non-failing challenge observation to a browser capture.
    pub fn with_browser_challenge(
        mut self,
        fact: BrowserChallengeFact,
    ) -> Result<Self, WebCaptureError> {
        validate_browser_challenge(&self.acquisition, &self.environment)?;
        if !fact.is_consistent() {
            return Err(WebCaptureError::InvalidBrowserChallenge);
        }
        self.browser_challenge = Some(fact);
        Ok(self)
    }

    /// Returns the derived aggregate completion state.
    pub const fn completeness(&self) -> CaptureCompleteness {
        self.completeness
    }
}

fn validate_execution(
    acquisition: &WebAcquisitionRecord,
    environment: &CaptureEnvironment,
    capabilities: &WebProviderCapabilityProfile,
) -> Result<(), WebCaptureError> {
    use crate::WebAcquisitionStrategy::{
        ContextBoundHttp, DirectHttp, DocumentNavigation, PageContextFetch,
    };

    let strategy = acquisition.request().strategy();
    let profile = capabilities.acquisition();
    let profile_matches = matches!(
        (strategy, profile),
        (DirectHttp(_), AcquisitionCapabilityProfile::DirectHttp)
            | (
                ContextBoundHttp(_),
                AcquisitionCapabilityProfile::ContextBoundHttp
            )
            | (
                PageContextFetch(_),
                AcquisitionCapabilityProfile::PageContextFetch
            )
            | (
                DocumentNavigation(_),
                AcquisitionCapabilityProfile::DocumentNavigation(_)
            )
    );
    if !profile_matches {
        return Err(WebCaptureError::AcquisitionCapabilityMismatch);
    }

    let executor = match (strategy, environment) {
        (DirectHttp(_) | ContextBoundHttp(_), CaptureEnvironment::Http(http)) => http.client(),
        (PageContextFetch(_) | DocumentNavigation(_), CaptureEnvironment::Browser(browser)) => {
            browser.controller()
        }
        _ => return Err(WebCaptureError::EnvironmentMismatch),
    };
    if executor != capabilities.producer() {
        return Err(WebCaptureError::CapabilityProducerMismatch);
    }

    match (profile, environment) {
        (
            AcquisitionCapabilityProfile::DocumentNavigation(profile),
            CaptureEnvironment::Browser(browser),
        ) if browser
            .mode()
            .as_known()
            .is_some_and(|mode| *mode != profile.mode()) =>
        {
            return Err(WebCaptureError::BrowserModeMismatch);
        }
        _ => {}
    }
    Ok(())
}

fn validate_capabilities(
    capabilities: &crate::WebArtifactCapabilitySet,
    results: &WebArtifactResults,
) -> Result<(), WebCaptureError> {
    validate_family(
        WebArtifactFamily::Source,
        capabilities.source(),
        results.source(),
    )?;
    validate_family(
        WebArtifactFamily::RenderedDom,
        capabilities.rendered_dom(),
        results.rendered_dom(),
    )?;
    validate_family(
        WebArtifactFamily::AccessibilityTree,
        capabilities.accessibility_tree(),
        results.accessibility_tree(),
    )?;
    validate_family(
        WebArtifactFamily::Network,
        capabilities.network(),
        results.network(),
    )?;
    validate_family(
        WebArtifactFamily::Cookies,
        capabilities.cookies(),
        results.cookies(),
    )?;
    validate_family(
        WebArtifactFamily::Storage,
        capabilities.storage(),
        results.storage(),
    )?;
    validate_family(
        WebArtifactFamily::Layout,
        capabilities.layout(),
        results.layout(),
    )?;
    validate_family(
        WebArtifactFamily::Visual,
        capabilities.visual(),
        results.visual(),
    )?;
    validate_family(
        WebArtifactFamily::RuntimeDiagnostics,
        capabilities.runtime_diagnostics(),
        results.runtime_diagnostics(),
    )?;
    Ok(())
}

fn validate_family<T>(
    family: WebArtifactFamily,
    capability: &ArtifactCapability,
    result: &ArtifactFamilyResult<T>,
) -> Result<(), WebCaptureError> {
    if matches!(result, ArtifactFamilyResult::NotRequested) {
        return Ok(());
    }
    let unsupported_result = matches!(result, ArtifactFamilyResult::Unsupported { .. });
    match (capability, unsupported_result) {
        (ArtifactCapability::Supported { multiplicity }, false) => {
            let count = result.artifacts().map_or(0, <[T]>::len);
            let exceeds = match multiplicity {
                ArtifactMultiplicity::ExactlyOne | ArtifactMultiplicity::AtMostOne => count > 1,
                ArtifactMultiplicity::Many => false,
            };
            if exceeds {
                return Err(WebCaptureError::ArtifactMultiplicityExceeded { family });
            }
        }
        (ArtifactCapability::Unsupported { .. }, true) => {}
        _ => return Err(WebCaptureError::CapabilityResultMismatch { family }),
    }
    Ok(())
}

fn validate_artifacts(
    acquisition: &WebAcquisitionRecord,
    environment: &CaptureEnvironment,
    observation: &crate::CaptureObservation,
    manifest: &WebArtifactManifest,
    relationships: &[WebArtifactRelationship],
) -> Result<(), WebCaptureError> {
    let artifacts = manifest.results().all_artifacts();
    let capture_activity = acquisition.receipt().id().activity_id();
    let window = observation.window();

    for (index, artifact) in artifacts.iter().enumerate() {
        let metadata = artifact.metadata();
        if metadata.provenance().activity_id() != capture_activity {
            return Err(WebCaptureError::ForeignArtifact);
        }
        if !browser_context_matches(artifact, environment, observation) {
            return Err(WebCaptureError::BrowserArtifactContextMismatch);
        }
        let generated_at = metadata.provenance().generated_at();
        if generated_at < window.started_at() || generated_at > window.finished_at() {
            return Err(WebCaptureError::ArtifactTimeOutsideWindow);
        }
        if artifacts
            .iter()
            .skip(index.saturating_add(1))
            .any(|other| other.metadata().reference() == metadata.reference())
        {
            return Err(WebCaptureError::DuplicateArtifact);
        }
    }

    if artifacts.iter().any(|artifact| {
        let Some(BrowserArtifactContext::Visual(visual)) = artifact.metadata().browser_context()
        else {
            return false;
        };
        if visual.layout_correlation != BrowserVisualLayoutCorrelation::SameDocumentEpochOnly {
            return false;
        }
        !artifacts.iter().any(|layout| {
            layout.family() == WebArtifactFamily::Layout
                && matches!(
                    layout.metadata().record().availability(),
                    ArtifactAvailability::Retained | ArtifactAvailability::Truncated
                )
                && matches!(
                    layout.metadata().browser_context(),
                    Some(BrowserArtifactContext::DocumentSnapshot { scope, captured_at })
                        if *scope == visual.scope
                            && Some(*captured_at) == visual.paired_layout_at
                            && *captured_at <= visual.at
                )
        })
    }) {
        return Err(WebCaptureError::BrowserArtifactContextMismatch);
    }

    let outputs = acquisition.receipt().receipt().outputs();
    if outputs.len() != artifacts.len()
        || artifacts.iter().any(|artifact| {
            !outputs
                .iter()
                .any(|output| output == artifact.metadata().record())
        })
    {
        return Err(WebCaptureError::ReceiptOutputMismatch);
    }

    for relationship in relationships {
        if relationship.references().iter().any(|reference| {
            !artifacts
                .iter()
                .any(|artifact| artifact.reference() == *reference)
        }) {
            return Err(WebCaptureError::ForeignRelationship);
        }
    }
    Ok(())
}

fn browser_context_matches(
    artifact: &WebArtifact,
    environment: &CaptureEnvironment,
    observation: &crate::CaptureObservation,
) -> bool {
    let metadata = artifact.metadata();
    let context = metadata.browser_context();
    if matches!(environment, CaptureEnvironment::Http(_)) {
        return context.is_none();
    }
    let payload_retained = matches!(
        metadata.record().availability(),
        ArtifactAvailability::Retained | ArtifactAvailability::Truncated
    );
    let family_context_matches = match (artifact.family(), context) {
        (WebArtifactFamily::Visual, Some(BrowserArtifactContext::Visual(visual))) => {
            let correlation_valid = match visual.layout_correlation {
                BrowserVisualLayoutCorrelation::SameDocumentEpochOnly => visual
                    .paired_layout_at
                    .is_some_and(|layout_at| layout_at <= visual.at),
                BrowserVisualLayoutCorrelation::Unavailable => visual.paired_layout_at.is_none(),
            };
            visual.width_pixels > 0
                && visual.height_pixels > 0
                && visual.viewport_width_css > 0
                && visual.viewport_height_css > 0
                && visual.device_scale_micro > 0
                && correlation_valid
        }
        (
            WebArtifactFamily::Source
            | WebArtifactFamily::RenderedDom
            | WebArtifactFamily::AccessibilityTree
            | WebArtifactFamily::Layout
            | WebArtifactFamily::Visual,
            None,
        ) => !payload_retained,
        (
            WebArtifactFamily::Source
            | WebArtifactFamily::RenderedDom
            | WebArtifactFamily::AccessibilityTree
            | WebArtifactFamily::Layout,
            Some(BrowserArtifactContext::DocumentSnapshot { .. }),
        )
        | (_, None) => true,
        _ => false,
    };
    if !family_context_matches {
        return false;
    }
    let Some(context) = context else {
        return true;
    };
    let (scope, at) = match context {
        BrowserArtifactContext::DocumentSnapshot { scope, captured_at } => (*scope, *captured_at),
        BrowserArtifactContext::Visual(visual) => (visual.scope, visual.at),
    };
    if scope.frame.0 == 0 || scope.epoch.0 == 0 {
        return false;
    }
    let Ok(micros) = i64::try_from(at.as_microseconds()) else {
        return false;
    };
    observation
        .window()
        .started_at()
        .checked_add_signed(TimeDelta::microseconds(micros))
        .is_some_and(|generated_at| generated_at == *metadata.provenance().generated_at())
}

fn derive_completeness(
    acquisition: &WebAcquisitionRecord,
    observation: &crate::CaptureObservation,
    results: &WebArtifactResults,
) -> CaptureCompleteness {
    let normal_termination = matches!(
        observation.termination(),
        CaptureTermination::Settled(_) | CaptureTermination::ControllerStopped(_)
    );
    let complete_results = results.all_complete_or_not_requested();
    let all_artifact_bytes_retained = results.all_artifacts().iter().all(|artifact| {
        artifact.metadata().record().availability() == ArtifactAvailability::Retained
    });
    if acquisition.receipt().receipt().outcome() == ActivityOutcome::Succeeded
        && normal_termination
        && complete_results
        && all_artifact_bytes_retained
    {
        CaptureCompleteness::Complete
    } else {
        CaptureCompleteness::Incomplete
    }
}
