import builtins
from collections.abc import Awaitable

__version__: str

class YosoiError(Exception):
    rust_type: str
    variant: str | None
    details: dict[str, object]
    source_chain: list[str]

class DocumentError(YosoiError): ...
class ParseError(YosoiError): ...
class LocatorError(YosoiError): ...
class PolicyError(YosoiError): ...
class ClosedResourceError(YosoiError): ...
class RequestError(YosoiError): ...
class MapError(YosoiError): ...
class SearchError(YosoiError): ...
class ContractError(YosoiError): ...

class Plan:
    def __init__(self, outputs_json: str) -> None: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(value: str) -> Plan: ...

class Document:
    def __init__(self, id: str, content: builtins.bytes, profile_json: str) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def byte_len(self) -> int: ...
    def profile(self) -> str: ...
    def document_class(self) -> str: ...
    def bytes(self) -> builtins.bytes: ...
    def validate_input(
        self, id: str, content: builtins.bytes, profile_json: str
    ) -> None: ...
    def locate(self, plan: Plan, policy_json: str | None = None) -> str: ...
    def parse(self, policy_json: str | None = None) -> ParsedDocument: ...

class ParsedDocument:
    @property
    def closed(self) -> bool: ...
    def locate(self, plan: Plan) -> str: ...
    def close(self) -> None: ...

def default_policy() -> str: ...
def validate_policy(value: str) -> str: ...
def policy_identity(value: str) -> str: ...

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

class PageRequest:
    def __init__(self, target: str) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def target(self) -> str: ...
    def validate(self, policy_json: str | None = None) -> None: ...
    def send(
        self,
        policy_json: str | None = None,
        cancellation: CancellationToken | None = None,
    ) -> Awaitable[Response]: ...

class Response:
    def to_json(self) -> str: ...
    def document(self, attempt: int, document: int) -> Document: ...

class MapRequest:
    def __init__(self, seed: str) -> None: ...
    def validate(self, policy_json: str | None = None) -> None: ...
    def send(
        self,
        policy_json: str | None = None,
        cancellation: CancellationToken | None = None,
    ) -> Awaitable[MapOutcome]: ...

class MapOutcome:
    def to_json(self) -> str: ...
    def response(self, index: int) -> Response: ...

class SearchRequest:
    def __init__(self, query: str) -> None: ...
    @property
    def id(self) -> str: ...
    def validate(self, policy_json: str | None = None) -> None: ...
    def send(
        self,
        policy_json: str | None = None,
        cancellation: CancellationToken | None = None,
    ) -> Awaitable[str]: ...

def wait_for_idle() -> Awaitable[None]: ...

class Contract:
    def __init__(self, schema_json: str) -> None: ...
    def identity(self) -> str: ...
    def extract(
        self, located_json: str, limits_json: str | None = None
    ) -> Extracted: ...

class Extracted:
    def to_json(self) -> str: ...
    def validate(self, limits_json: str | None = None) -> ContractOutcome: ...

class ContractOutcome:
    def to_json(self) -> str: ...
    def require_all(self) -> str: ...
    def to_archived(self, schema_json: str) -> str: ...

def validate_money(value: str) -> str: ...

browser_enabled: bool

def public_providers() -> str: ...
def public_provider_endpoint(provider: str, domain: str) -> str: ...
def search_result_url(value: str) -> str: ...
def rejection_message(value: str) -> str: ...
def map_value_compare(kind: str, left_json: str, right_json: str) -> int: ...
def contract_value_type_id(money: bool) -> str: ...
def validate_query(declaration_json: str) -> None: ...
def projected_value_equal(left: str, right: str) -> bool: ...
def effective_policy(value: str) -> str: ...
def policy_snapshot(value: str) -> str: ...
def validation_limits_defaults() -> str: ...
def contract_schema_identity(value: str) -> str: ...
def validate_profile(profile_json: str) -> str: ...
def profile_class(profile_json: str) -> str: ...
def public_provider_name(value: str) -> str: ...
def field_schema_validate(value: str) -> None: ...
def validate_namespace(declaration_json: str, prefix: str | None, uri: str) -> None: ...
def validate_region_id(value: str) -> None: ...
def validate_output_id(value: str) -> None: ...
def validate_locator(declaration_json: str) -> None: ...
def authored_query_info(value: str) -> str: ...
def compiled_query_info(value: str) -> str: ...
def compiled_query_namespace(value: str, prefix: str | None, uri: str) -> str: ...
def validate_domain_model(kind: str, value_json: str) -> str: ...
def activity_identity(value: str | None, capture: bool) -> str: ...
def activity_identity_bytes(value: str) -> list[int]: ...
def policy_component(
    kind: str, component_json: str | None, operation: str, args_json: str | None
) -> str: ...
