"""Yosoi: AI-powered CSS selector discovery and web scraping.

The public API is resolved **lazily** (PEP 562). ``import yosoi`` no longer
eagerly pulls the heavy dependency graph; each name is imported from its
submodule on first access instead.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from yosoi._lazy import lazy_exports

try:
    __version__ = version('yosoi')
except PackageNotFoundError:
    __version__ = 'unknown'

_LAZY: dict[str, str] = {
    # api
    'fingerprint': 'yosoi.api',
    'scrape': 'yosoi.api',
    'scrape_many': 'yosoi.api',
    'scrape_sync': 'yosoi.api',
    # display
    'show': 'yosoi.reporting',
    # policy-first model/provider helpers
    'alibaba': 'yosoi.policy',
    'anthropic': 'yosoi.policy',
    'azure': 'yosoi.policy',
    'bedrock': 'yosoi.policy',
    'cerebras': 'yosoi.policy',
    'claude_sdk': 'yosoi.policy',
    'deepseek': 'yosoi.policy',
    'fireworks': 'yosoi.policy',
    'gemini': 'yosoi.policy',
    'github': 'yosoi.policy',
    'grok': 'yosoi.policy',
    'groq': 'yosoi.policy',
    'heroku': 'yosoi.policy',
    'huggingface': 'yosoi.policy',
    'litellm': 'yosoi.policy',
    'mistral': 'yosoi.policy',
    'moonshotai': 'yosoi.policy',
    'nebius': 'yosoi.policy',
    'ollama': 'yosoi.policy',
    'openai': 'yosoi.policy',
    'opencode': 'yosoi.policy',
    'openrouter': 'yosoi.policy',
    'ovhcloud': 'yosoi.policy',
    'provider': 'yosoi.policy',
    'sambanova': 'yosoi.policy',
    'together': 'yosoi.policy',
    'vercel': 'yosoi.policy',
    'vertexai': 'yosoi.policy',
    'xai': 'yosoi.policy',
    # crawler
    'CrawlRunSummary': 'yosoi.core.crawler',
    'crawl': 'yosoi.core.crawler.run',
    # pipeline
    'Pipeline': 'yosoi.core.pipeline',
    # policies
    'CrawlBudget': 'yosoi.policy',
    'CrawlPolicy': 'yosoi.policy',
    'CrawlPresetName': 'yosoi.policy',
    'CrawlRuntimeConfig': 'yosoi.policy',
    'CrawlSafety': 'yosoi.policy',
    'CrawlTarget': 'yosoi.policy',
    'DiscoveryPolicy': 'yosoi.policy',
    'DownloadPolicy': 'yosoi.policy',
    'EscalationPolicy': 'yosoi.policy',
    'FingerprintPolicy': 'yosoi.policy',
    'ModelPolicy': 'yosoi.policy',
    'OutputPolicy': 'yosoi.policy',
    'PagePolicy': 'yosoi.policy',
    'PageRuntimeConfig': 'yosoi.policy',
    'Policy': 'yosoi.policy',
    'PolicyCheck': 'yosoi.policy',
    'ResolvedRunSpec': 'yosoi.policy',
    'SchedulerPolicy': 'yosoi.policy',
    'ScrapePolicy': 'yosoi.policy',
    'SecretRef': 'yosoi.policy',
    'TelemetryPolicy': 'yosoi.policy',
    'check_policy': 'yosoi.policy',
    'policy_arn': 'yosoi.policy',
    'resolve_crawl_policy': 'yosoi.policy',
    # generalization
    'PageAcquisition': 'yosoi.core.page',
    'PageSnapshot': 'yosoi.core.page',
    'PageFingerprint': 'yosoi.generalization.fingerprint',
    # integration transports
    'ClaudeSDKModel': 'yosoi.integrations',
    'OpenCodeModel': 'yosoi.integrations',
    # models
    'Contract': 'yosoi.models.contract',
    'DownloadRecord': 'yosoi.models.download',
    'JobPosting': 'yosoi.models.defaults',
    'NewsArticle': 'yosoi.models.defaults',
    'Product': 'yosoi.models.defaults',
    'Video': 'yosoi.models.defaults',
    'FieldSelectors': 'yosoi.models.selectors',
    'SelectorEntry': 'yosoi.models.selectors',
    'SelectorLevel': 'yosoi.models.selectors',
    'attr': 'yosoi.models.selectors',
    'css': 'yosoi.models.selectors',
    'discover': 'yosoi.models.selectors',
    'global_id': 'yosoi.models.selectors',
    'jsonld': 'yosoi.models.selectors',
    'regex': 'yosoi.models.selectors',
    'role': 'yosoi.models.selectors',
    'visual': 'yosoi.models.selectors',
    'xpath': 'yosoi.models.selectors',
    'CacheVerdict': 'yosoi.models.snapshot',
    'SelectorSnapshot': 'yosoi.models.snapshot',
    'SnapshotMap': 'yosoi.models.snapshot',
    'SnapshotStatus': 'yosoi.models.snapshot',
    # semantic types
    'Author': 'yosoi.types',
    'BodyText': 'yosoi.types',
    'Datetime': 'yosoi.types',
    'Field': 'yosoi.types',
    'File': 'yosoi.types',
    'Price': 'yosoi.types',
    'Rating': 'yosoi.types',
    'Title': 'yosoi.types',
    'Url': 'yosoi.types',
    'js': 'yosoi.types',
    'register_coercion': 'yosoi.types',
    # utils
    'resolve_contract': 'yosoi.utils.contracts',
    'load_urls_from_file': 'yosoi.utils.urls',
    # contract IO — save/load contracts as JSON files
    'save_contract': 'yosoi.utils.contract_io',
    'load_contract': 'yosoi.utils.contract_io',
    # selector IO — save/load selectors as standalone JSON files
    'save_selectors': 'yosoi.utils.selector_io',
    'load_selectors': 'yosoi.utils.selector_io',
}

__all__ = [
    'Author',
    'BodyText',
    'CacheVerdict',
    'ClaudeSDKModel',
    'Contract',
    'CrawlBudget',
    'CrawlPolicy',
    'CrawlRunSummary',
    'CrawlRuntimeConfig',
    'CrawlSafety',
    'CrawlTarget',
    'Datetime',
    'DiscoveryPolicy',
    'DownloadPolicy',
    'DownloadRecord',
    'EscalationPolicy',
    'Field',
    'FieldSelectors',
    'File',
    'FingerprintPolicy',
    'JobPosting',
    'ModelPolicy',
    'NewsArticle',
    'OpenCodeModel',
    'OutputPolicy',
    'PageAcquisition',
    'PageFingerprint',
    'PagePolicy',
    'PageRuntimeConfig',
    'PageSnapshot',
    'Pipeline',
    'Policy',
    'PolicyCheck',
    'Price',
    'Rating',
    'ResolvedRunSpec',
    'SchedulerPolicy',
    'ScrapePolicy',
    'SecretRef',
    'SelectorEntry',
    'SelectorLevel',
    'SelectorSnapshot',
    'SnapshotMap',
    'SnapshotStatus',
    'TelemetryPolicy',
    'Title',
    'Url',
    'Video',
    'alibaba',
    'anthropic',
    'attr',
    'azure',
    'bedrock',
    'cerebras',
    'check_policy',
    'claude_sdk',
    'crawl',
    'css',
    'deepseek',
    'discover',
    'fingerprint',
    'fireworks',
    'gemini',
    'github',
    'global_id',
    'grok',
    'groq',
    'heroku',
    'huggingface',
    'js',
    'jsonld',
    'litellm',
    'load_contract',
    'load_selectors',
    'load_urls_from_file',
    'mistral',
    'moonshotai',
    'nebius',
    'ollama',
    'openai',
    'opencode',
    'openrouter',
    'ovhcloud',
    'policy_arn',
    'provider',
    'regex',
    'register_coercion',
    'resolve_contract',
    'resolve_crawl_policy',
    'role',
    'sambanova',
    'save_contract',
    'save_selectors',
    'scrape',
    'scrape_many',
    'scrape_sync',
    'show',
    'together',
    'vercel',
    'vertexai',
    'visual',
    'xai',
    'xpath',
]

__getattr__, __dir__ = lazy_exports(__name__, globals(), _LAZY)
