"""Yosoi: AI-powered CSS selector discovery and web scraping.

The public API is resolved **lazily** (PEP 562). ``import yosoi`` no longer
eagerly pulls the heavy dependency graph (pydantic-ai and its provider SDKs, the
Claude/OpenCode transports, parsel, dateparser, …); each name is imported from
its submodule on first access instead. This cuts ``import yosoi`` — and every
short-lived subprocess that only needs a slice of the package, e.g. the
``yosoi-validator-mcp`` server — from ~1.6s to well under a second.

Static typing is unaffected: ``yosoi/__init__.pyi`` declares every name
statically, so type-checkers and IDEs see the full API. Keep that stub and the
``_LAZY`` map below in lockstep with each other.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from yosoi._lazy import lazy_exports

try:
    __version__ = version('yosoi')
except PackageNotFoundError:
    __version__ = 'unknown'

# Public name -> submodule that defines it. Resolved on first attribute access.
_LAZY: dict[str, str] = {
    # api
    'fetch': 'yosoi.api',
    'fingerprint': 'yosoi.api',
    'map': 'yosoi.api',
    'search': 'yosoi.api',
    'scrape': 'yosoi.api',
    'scrape_many': 'yosoi.api',
    'scrape_sync': 'yosoi.api',
    # recipes
    'Recipe': 'yosoi.recipe',
    'RecipeMetadata': 'yosoi.recipe',
    'RecipePolicy': 'yosoi.policy',
    'RecipeTrust': 'yosoi.recipe',
    'RecipeValidation': 'yosoi.recipe',
    'install_recipe': 'yosoi.recipe',
    'load_recipe': 'yosoi.recipe',
    'mint_recipe': 'yosoi.recipe',
    'selector_map': 'yosoi.recipe',
    # operation contracts
    'ContractRef': 'yosoi.operations',
    'ContentRequest': 'yosoi.operations',
    'ContentResult': 'yosoi.operations',
    'ContentUnitResult': 'yosoi.operations',
    'CrawlRequest': 'yosoi.operations',
    'CrawlResult': 'yosoi.operations',
    'FetchRequest': 'yosoi.operations',
    'FetchResult': 'yosoi.operations',
    'FetchUnitResult': 'yosoi.operations',
    'MapHost': 'yosoi.core.site_map',
    'MapRequest': 'yosoi.core.site_map',
    'MapResult': 'yosoi.core.site_map',
    'MapSitemap': 'yosoi.core.site_map',
    'MapUrl': 'yosoi.core.site_map',
    'ScrapeRequest': 'yosoi.operations',
    'ScrapeResult': 'yosoi.operations',
    'ScrapeUnitResult': 'yosoi.operations',
    'SearchHit': 'yosoi.operations',
    'SearchRequest': 'yosoi.operations',
    'SearchResult': 'yosoi.operations',
    'execute_content': 'yosoi.operations',
    'execute_crawl': 'yosoi.operations',
    'execute_fetch': 'yosoi.operations',
    'execute_map': 'yosoi.operations',
    'execute_search': 'yosoi.operations',
    'execute_scrape': 'yosoi.operations',
    'run_content': 'yosoi.operations',
    'run_crawl': 'yosoi.operations',
    'run_fetch': 'yosoi.operations',
    'run_map': 'yosoi.operations',
    'run_search': 'yosoi.operations',
    'run_scrape': 'yosoi.operations',
    # display
    'show': 'yosoi.reporting',
    # policy-first model/provider helpers
    'alibaba': 'yosoi.policy',
    'anthropic': 'yosoi.policy',
    'azure': 'yosoi.policy',
    'bedrock': 'yosoi.policy',
    'cerebras': 'yosoi.policy',
    'claude_sdk': 'yosoi.policy',
    'deepseek': 'yosoi.policy',
    'fireworks': 'yosoi.policy',
    'gemini': 'yosoi.policy',
    'github': 'yosoi.policy',
    'grok': 'yosoi.policy',
    'groq': 'yosoi.policy',
    'heroku': 'yosoi.policy',
    'huggingface': 'yosoi.policy',
    'litellm': 'yosoi.policy',
    'mistral': 'yosoi.policy',
    'moonshotai': 'yosoi.policy',
    'nebius': 'yosoi.policy',
    'ollama': 'yosoi.policy',
    'openai': 'yosoi.policy',
    'opencode': 'yosoi.policy',
    'openrouter': 'yosoi.policy',
    'ovhcloud': 'yosoi.policy',
    'provider': 'yosoi.policy',
    'sambanova': 'yosoi.policy',
    'together': 'yosoi.policy',
    'vercel': 'yosoi.policy',
    'vertexai': 'yosoi.policy',
    'xai': 'yosoi.policy',
    # crawler
    'CrawlRunSummary': 'yosoi.core.crawler',
    'crawl': 'yosoi.core.crawler.run',
    # pipeline
    'Pipeline': 'yosoi.core.pipeline',
    # policies
    'CrawlBudget': 'yosoi.policy',
    'CrawlPolicy': 'yosoi.policy',
    'CrawlPresetName': 'yosoi.policy',
    'CrawlRuntimeConfig': 'yosoi.policy',
    'CrawlSafety': 'yosoi.policy',
    'CrawlTarget': 'yosoi.policy',
    'DiscoveryPolicy': 'yosoi.policy',
    'DownloadPolicy': 'yosoi.policy',
    'EscalationPolicy': 'yosoi.policy',
    'FingerprintPolicy': 'yosoi.policy',
    'ModelPolicy': 'yosoi.policy',
    'OutputPolicy': 'yosoi.policy',
    'PagePolicy': 'yosoi.policy',
    'BrowserProfilePolicy': 'yosoi.policy',
    'PageRuntimeConfig': 'yosoi.policy',
    'Policy': 'yosoi.policy',
    'PolicyCheck': 'yosoi.policy',
    'ResolvedRunSpec': 'yosoi.policy',
    'SchedulerPolicy': 'yosoi.policy',
    'ScrapePolicy': 'yosoi.policy',
    'SearchPolicy': 'yosoi.policy',
    'SecretRef': 'yosoi.policy',
    'TelemetryPolicy': 'yosoi.policy',
    'check_policy': 'yosoi.policy',
    'policy_arn': 'yosoi.policy',
    'resolve_crawl_policy': 'yosoi.policy',
    # generalization
    'PageAcquisition': 'yosoi.core.page',
    'PageSnapshot': 'yosoi.core.page',
    'PageFingerprint': 'yosoi.generalization.fingerprint',
    # integration transports
    'ClaudeSDKModel': 'yosoi.integrations',
    'OpenCodeModel': 'yosoi.integrations',
    # models
    'Contract': 'yosoi.models.contract',
    'DownloadRecord': 'yosoi.models.download',
    'JobPosting': 'yosoi.models.defaults',
    'NewsArticle': 'yosoi.models.defaults',
    'Product': 'yosoi.models.defaults',
    'Video': 'yosoi.models.defaults',
    'FieldSelectors': 'yosoi.models.selectors',
    'SelectorEntry': 'yosoi.models.selectors',
    'SelectorLevel': 'yosoi.models.selectors',
    'attr': 'yosoi.models.selectors',
    'css': 'yosoi.models.selectors',
    'discover': 'yosoi.models.selectors',
    'global_id': 'yosoi.models.selectors',
    'jsonld': 'yosoi.models.selectors',
    'regex': 'yosoi.models.selectors',
    'role': 'yosoi.models.selectors',
    'visual': 'yosoi.models.selectors',
    'xpath': 'yosoi.models.selectors',
    'CacheVerdict': 'yosoi.models.snapshot',
    'SelectorSnapshot': 'yosoi.models.snapshot',
    'SnapshotMap': 'yosoi.models.snapshot',
    'SnapshotStatus': 'yosoi.models.snapshot',
    # semantic types (importing these registers their coercions)
    'Author': 'yosoi.types',
    'BodyText': 'yosoi.types',
    'Datetime': 'yosoi.types',
    'Field': 'yosoi.types',
    'File': 'yosoi.types',
    'Price': 'yosoi.types',
    'Rating': 'yosoi.types',
    'Title': 'yosoi.types',
    'Url': 'yosoi.types',
    'js': 'yosoi.types',
    'register_coercion': 'yosoi.types',
    # utils
    'resolve_contract': 'yosoi.utils.contracts',
    'load_urls_from_file': 'yosoi.utils.urls',
}

__all__ = [
    'Author',
    'BodyText',
    'BrowserProfilePolicy',
    'CacheVerdict',
    'ClaudeSDKModel',
    'ContentRequest',
    'ContentResult',
    'ContentUnitResult',
    'Contract',
    'CrawlBudget',
    'CrawlPolicy',
    'CrawlRunSummary',
    'CrawlRuntimeConfig',
    'CrawlSafety',
    'CrawlTarget',
    'Datetime',
    'DiscoveryPolicy',
    'DownloadPolicy',
    'DownloadRecord',
    'EscalationPolicy',
    'FetchRequest',
    'FetchResult',
    'FetchUnitResult',
    'Field',
    'FieldSelectors',
    'File',
    'FingerprintPolicy',
    'JobPosting',
    'MapHost',
    'MapRequest',
    'MapResult',
    'MapSitemap',
    'MapUrl',
    'ModelPolicy',
    'NewsArticle',
    'OpenCodeModel',
    'OutputPolicy',
    'PageAcquisition',
    'PageFingerprint',
    'PagePolicy',
    'PageRuntimeConfig',
    'PageSnapshot',
    'Pipeline',
    'Policy',
    'PolicyCheck',
    'Price',
    'Rating',
    'Recipe',
    'RecipeMetadata',
    'RecipePolicy',
    'RecipeTrust',
    'RecipeValidation',
    'ResolvedRunSpec',
    'SchedulerPolicy',
    'ScrapePolicy',
    'SearchHit',
    'SearchPolicy',
    'SearchRequest',
    'SearchResult',
    'SecretRef',
    'SelectorEntry',
    'SelectorLevel',
    'SelectorSnapshot',
    'SnapshotMap',
    'SnapshotStatus',
    'TelemetryPolicy',
    'Title',
    'Url',
    'Video',
    'alibaba',
    'anthropic',
    'attr',
    'azure',
    'bedrock',
    'cerebras',
    'check_policy',
    'claude_sdk',
    'crawl',
    'css',
    'deepseek',
    'discover',
    'execute_content',
    'execute_fetch',
    'fetch',
    'fingerprint',
    'fireworks',
    'gemini',
    'github',
    'global_id',
    'grok',
    'groq',
    'heroku',
    'huggingface',
    'install_recipe',
    'js',
    'jsonld',
    'litellm',
    'load_recipe',
    'load_urls_from_file',
    'map',
    'mint_recipe',
    'mistral',
    'moonshotai',
    'nebius',
    'ollama',
    'openai',
    'opencode',
    'openrouter',
    'ovhcloud',
    'policy_arn',
    'provider',
    'recipe',
    'regex',
    'register_coercion',
    'resolve_contract',
    'resolve_crawl_policy',
    'role',
    'run_content',
    'run_fetch',
    'sambanova',
    'scrape',
    'scrape_many',
    'scrape_sync',
    'search',
    'selector_map',
    'show',
    'together',
    'vercel',
    'vertexai',
    'visual',
    'xai',
    'xpath',
]


__getattr__, __dir__ = lazy_exports(__name__, globals(), _LAZY)
