#!/usr/bin/env bash
# Generic Chromium/CDP runtime, adapted from the existing VoidCrawl images. All mutable state is generated under RUNTIME_DIR.
set -euo pipefail

BROWSER_MODE="${BROWSER_MODE:-headful}"
case "$BROWSER_MODE" in headless|headful) ;; *) echo "invalid BROWSER_MODE" >&2; exit 64 ;; esac
RUNTIME_DIR="${RUNTIME_DIR:-/tmp/yosoi}"
XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-$RUNTIME_DIR/xdg}"
CONFIG_DIR="$RUNTIME_DIR/config"
LOG_DIR="$RUNTIME_DIR/logs"
PROFILE_ROOT="${CHROME_PROFILES_DIR:-$RUNTIME_DIR/profiles}"
DBUS_SOCKET="$RUNTIME_DIR/dbus/session_bus_socket"

require_uint() {
   [[ "${2:-}" =~ ^[1-9][0-9]*$ ]] || {
       echo "[config] $1 must be a positive integer (got '${2:-}')" >&2
       exit 64
   }
}

require_uint BROWSER_COUNT "${BROWSER_COUNT:-2}"
require_uint CDP_PORT_BASE "${CDP_PORT_BASE:-19222}"
require_uint VNC_PORT_BASE "${VNC_PORT_BASE:-5900}"
require_uint VNC_WIDTH "${VNC_WIDTH:-1920}"
require_uint VNC_HEIGHT "${VNC_HEIGHT:-1080}"

case "${CHROME_NO_SANDBOX:-0}" in
   0|false|no) ;;
   *) echo "The Chromium sandbox is required" >&2; exit 64 ;;
esac
CHROME_BIN="${CHROME_BIN:-/usr/bin/chromium}"
if [ "$(id -u)" = 0 ]; then echo "Run as a non-root user" >&2; exit 64; fi
if [ "${VIEWER_MODE:-disabled}" != disabled ] && [ "$BROWSER_MODE" != headful ]; then
    echo "Viewer access requires headful mode" >&2; exit 64
fi

BROWSER_COUNT="${BROWSER_COUNT:-2}"
CDP_PORT_BASE="${CDP_PORT_BASE:-19222}"
VNC_PORT_BASE="${VNC_PORT_BASE:-5900}"
VNC_WIDTH="${VNC_WIDTH:-1920}"
VNC_HEIGHT="${VNC_HEIGHT:-1080}"
if [ "${#BROWSER_COUNT}" -gt 2 ] || [ "$BROWSER_COUNT" -gt 8 ]; then echo "BROWSER_COUNT must be 1..8" >&2; exit 64; fi
for port in "$CDP_PORT_BASE" "$VNC_PORT_BASE"; do
    if [ "${#port}" -gt 5 ] || [ "$port" -lt 1024 ] || [ "$port" -gt "$((65536 - BROWSER_COUNT))" ]; then
        echo "Invalid port range" >&2; exit 64
    fi
done
for dimension in "$VNC_WIDTH" "$VNC_HEIGHT"; do
    if [ "${#dimension}" -gt 4 ] || [ "$dimension" -gt 8192 ]; then echo "Invalid display size" >&2; exit 64; fi
done
export RUNTIME_DIR XDG_RUNTIME_DIR BROWSER_COUNT CDP_PORT_BASE VNC_PORT_BASE VNC_WIDTH VNC_HEIGHT BROWSER_MODE CHROME_BIN

# Runtime paths are deliberately user-owned: the image can run with cap-drop=ALL
# and no-new-privileges, and never mutates /etc, /run, or /var at startup.
umask 077
mkdir -p "$XDG_RUNTIME_DIR" "$CONFIG_DIR" "$LOG_DIR" "$RUNTIME_DIR/dbus" \
   "$RUNTIME_DIR/viewer" "$PROFILE_ROOT"
chmod 0700 "$RUNTIME_DIR" "$XDG_RUNTIME_DIR" "$CONFIG_DIR" "$RUNTIME_DIR/dbus" \
   "$RUNTIME_DIR/viewer" "$PROFILE_ROOT"

# GPU selection only reads host device metadata. The host must grant UID 10001
# access to /dev/dri (normally via HOST_RENDER_GID in Compose); this entrypoint
# never edits groups.
detect_gpu() {
    if [ -e /dev/dri/renderD128 ]; then
        basename "$(readlink -f /sys/class/drm/renderD128/device/driver 2>/dev/null || echo unknown)"
    elif [ -e /dev/nvidia0 ]; then
        echo nvidia
    else
        echo none
    fi
}

GPU_DRIVER=$(detect_gpu)
case "$GPU_DRIVER" in
    amdgpu|i915|xe)
        export WLR_RENDERER="${WLR_RENDERER:-gles2}"
        ;;
    nvidia)
        export WLR_RENDERER="${WLR_RENDERER:-gles2}"
        export SWAY_EXTRA_ARGS="${SWAY_EXTRA_ARGS:---unsupported-gpu}"
        ;;
    *)
        export WLR_RENDERER="${WLR_RENDERER:-pixman}"
        export WLR_RENDERER_ALLOW_SOFTWARE="${WLR_RENDERER_ALLOW_SOFTWARE:-1}"
        ;;
esac
export SWAY_EXTRA_ARGS="${SWAY_EXTRA_ARGS:-}"
echo "[gpu] driver=$GPU_DRIVER renderer=$WLR_RENDERER"

write_sway_config() {
    local config="$CONFIG_DIR/sway.conf" i x=0
    {
        echo '# Generated by Yosoi Chromium entrypoint; do not edit.'
        for ((i = 1; i <= BROWSER_COUNT; i++)); do
            printf 'output HEADLESS-%s resolution %sx%s position %s 0\n' "$i" "$VNC_WIDTH" "$VNC_HEIGHT" "$x"
            printf 'workspace %s output HEADLESS-%s\n' "$i" "$i"
            x=$((x + VNC_WIDTH))
        done
        cat <<'EOF'
default_border none
default_floating_border none
titlebar_border_thickness 0
titlebar_padding 0 0
output * bg #1a1a2e solid_color
EOF
        for ((i = 1; i <= BROWSER_COUNT; i++)); do
            printf 'for_window [app_id="^chrome-%s$"] move workspace number %s, fullscreen enable\n' "$i" "$i"
            printf 'exec_always swaymsg output HEADLESS-%s dpms on\n' "$i"
        done
        echo 'for_window [app_id=".*"] fullscreen enable'
    } > "$config"
}

write_supervisor_config() {
    local MODE_ARGS="--headless=new --hide-scrollbars --mute-audio"
    if [ "$BROWSER_MODE" = headful ]; then MODE_ARGS="--class=chrome-PLACEHOLDER --ozone-platform=wayland"; fi
    local config="$CONFIG_DIR/supervisord.conf" i cdp_port profile_dir
    cat > "$config" <<EOF
[supervisord]
nodaemon=true
logfile=$LOG_DIR/supervisord.log
pidfile=$RUNTIME_DIR/supervisord.pid
childlogdir=$LOG_DIR

[unix_http_server]
file=$RUNTIME_DIR/supervisor.sock
chmod=0600

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://$RUNTIME_DIR/supervisor.sock

[program:dbus]
command=dbus-daemon --session --nofork --nopidfile --address=unix:path=$DBUS_SOCKET
autostart=true
autorestart=true
priority=5
stdout_logfile=$LOG_DIR/dbus.log
redirect_stderr=true

EOF
    if [ "$BROWSER_MODE" = headful ]; then
        cat >> "$config" <<EOF
[program:sway]
command=sway $SWAY_EXTRA_ARGS -c $CONFIG_DIR/sway.conf
environment=XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR",WLR_BACKENDS="headless",WLR_HEADLESS_OUTPUTS="$BROWSER_COUNT",WLR_LIBINPUT_NO_DEVICES="1",WLR_NO_HARDWARE_CURSORS="1",WLR_RENDERER="$WLR_RENDERER",LIBSEAT_BACKEND="noop"
autostart=true
autorestart=true
priority=10
stdout_logfile=$LOG_DIR/sway.log
redirect_stderr=true
EOF
    fi

    for ((i = 1; i <= BROWSER_COUNT; i++)); do
        cdp_port=$((CDP_PORT_BASE + i - 1))
        profile_dir="$PROFILE_ROOT/chrome-profile-$i"
        mkdir -p "$profile_dir"
        if [ "$BROWSER_MODE" = headful ]; then MODE_ARGS="--class=chrome-$i --ozone-platform=wayland"; fi
        cat >> "$config" <<EOF

[program:chrome-$i]
command=$CHROME_BIN $MODE_ARGS --remote-allow-origins=* --disable-breakpad --disable-dev-shm-usage --no-first-run --no-service-autorun --no-default-browser-check --no-pings --password-store=basic --disable-session-crashed-bubble --disable-search-engine-choice-screen --homepage=about:blank --enable-gpu --ignore-gpu-blocklist --use-angle=vulkan --disable-extensions --remote-debugging-port=$cdp_port --user-data-dir=$profile_dir about:blank
environment=XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR",WAYLAND_DISPLAY="wayland-1",DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_SOCKET",DISPLAY=""
autostart=true
autorestart=true
startsecs=5
priority=30
stdout_logfile=$LOG_DIR/chrome-$i.log
redirect_stderr=true
EOF
    done
}

if [ "$BROWSER_MODE" = headful ]; then write_sway_config; fi
write_supervisor_config

echo "[start] uid=$(id -u) browsers=$BROWSER_COUNT cdp_base=$CDP_PORT_BASE viewer_mode=${VIEWER_MODE:-disabled}"
echo "[start] runtime=$RUNTIME_DIR profiles=$PROFILE_ROOT"
exec supervisord -c "$CONFIG_DIR/supervisord.conf"
